- name: Testing ping module
  hosts: all
  become: true
  tasks:
          - name: installing apache2
            apt:
              name: apache2
              state: latest
          - name: installing telnet
            apt:
              name: telnet
              state: latest
          - name: restarting apache2 service
            service:
                name: apache2
                state: restarted
          - name: installing tomcat9
            apt:
                name: tomcat9
                state: latest
          - name: starting tomcat9 service
            service:
                name: tomcat9
                state: started
          - name: install maven
            apt:
                name: maven
                state: present
          - name: run mvn package
            shell: "mvn package"
