- name: Testing ping module
  hosts: all
  become: true
  vars:
          directory_name: working_directory
  tasks:
          - name: create working directory
            file:
                path: "{{ directory_name }}"
                state: directory
          - name: installing tomcat9
            apt:
                name: tomcat9
                state: latest
          - name: starting tomcat9 service
            service:
                name: tomcat9
                state: started
          - name: install maven
            apt:
                name: maven
                state: present
          - name: git checkout
            git:
                repo: 'https://github.com/SayamGanguly/java-hello-world-with-maven.git'
                dest: "{{ directory_name }}"
          - name: register ls result
            command: ls
            register: res
          - name: display result
            debug:
                msg: "{{ res.stdout }}"
          - name: run mvn package
            command: mvn -f "{{ directory_name }}"/pom.xml package
          - name: copy jar file
            copy:
                src: /home/labsuser/working_directory/target/jb-hello-world-maven-0.2.0.jar
                dest: /var/lib/tomcat9/webapps/jb-hello-world-maven-0.2.0.jar
          - name: Restarting tomcat9
            service:
                name: tomcat9
                state: restarted
